services:
  app: 
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    user: "1000:1000"
    volumes:
      - ./src:/app
    networks:
      - Laravel_network

  web:   
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
    networks:
      - Laravel_network

  db:  
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3308:3306
    env_file:
        - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE} //.envファイルに記述
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} //.envファイルに記述
      MYSQL_PASSWORD: ${DB_PASSWORD} //.envファイルに記述
      MYSQL_USER: ${DB_USERNAME}  //.envファイルに記述 
      
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - Laravel_network
      
volumes:
  mysql-volume:

networks:
  Laravel_network:
    driver: bridge